export {default as CustomerMain} from '../components/CustomerMain';
export {default as Profile} from '../menuPage/Profile'; 
export {default as Notice} from '../menuPage/Notice'; 
export {default as BoardList} from '../board/BoardList'; 
export {default as Map} from '../menuPage/Map'; 
export {default as Think} from '../menuPage/Think'; 
export {default as BoardView} from '../board/BoardView';
export {default as BoardRouter} from '../board/BoardRouter';
export {default as LoginView} from '../members/LoginView';